### ISSUE TITLE
API router

### ISSUE THREAD

**Issue by stevetoro** [daveoy/capstone-project-2-expresso#3]
https://github.com/daveoy/capstone-project-2-expresso/blob/master/api.js

You should move your actual API into its own designated folder, you shouldn't just have a few loose files in the project root being used as a router. 

This makes your API a little hard to look through and that ultimately might make it unnecessarily difficult to maintain.

**Comment by daveoy** [comment]
yeah i thoguht about this when i was putting this project together, will keep that in mind
