### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by stevetoro** [daveoy/capstone-project-2-expresso#4]
Satisfactory 👍 

You've demonstrated a clear proficiency with JavaScript objects and arrays as well as the general procedure of accessing requests and serving responses, including using the callback pattern which is commonly used in asynchronous tasks like HTTP requests and Database transactions. You've properly created your database via a migrations file and consumed that database to serve requests from your API. 

You're well on your way to designing and developing APIs, great job!

**Comment by daveoy** [comment]
thanks for your comments steve! was a great course.
